name: Auto Merge PR

on:
  pull_request:
    types: [synchronize]

jobs:
  run-tests-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Auto Merge PR
        if: ${{ success() }}
        uses: repo-sync/github-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.head_ref }}
          target_branch: ${{ github.base_ref }}
          merge_method: merge
          delete_source_branch: true
